:schedule:
  currency-worker:
    cron: '0 13 */1 * * *'   # Runs once per minute
    class: CurrencyWorker

:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [myqueue, 2]